#!/bin/bash
# Define an array of directories to convert
directories=("_githooks" "_gitignore" "_bundle" "_eslintignore" "_eslintrc.js" "_prettierrc.js" "_node-version" "_gitlab-ci.yml" "_watchmanconfig")

# Loop through each directory and convert it
for dir in "${directories[@]}"; do
  # Check if the directory exists
  if [ -f "$dir" ]; then
    # Copy all files from the underscored directory to the period directory
    cp -r "$dir" ".${dir/_/}"

    # Delete the underscored directory
    rm -rf "$dir"
  elif [ -d "$dir" ]; then
    # Copy all files from the underscored directory to the period directory
    cp -r "$dir/." ".${dir/_/}"

    # Delete the underscored directory
    rm -rf "$dir"
  fi
done

# ios/_xcode_env to ios/.xcode_env
# code below:
if [ -f "ios/_xcode_env" ]; then
  cp -r ios/_xcode_env ios/.xcode_env
  rm -rf ios/_xcode_env
fi

echo "Init script completed"