#!/bin/bash
# get PROJECT_PATH as first parameter
PROJECT_PATH=$1
# Define an array of directories to convert
directories=("_githooks" "_gitignore" "_bundle" "_eslintignore" "_eslintrc.js" "_prettierrc.js" "_node-version" "_gitlab-ci.yml" "_watchmanconfig" "_husky")

# Loop through each directory and convert it
for dir in "${directories[@]}"; do
  # append PROJECT_PATH to dir
  dir="$PROJECT_PATH/$dir"
  # Check if the directory exists
  if [ -f "$dir" ]; then
    # Copy all files from the underscored directory to the period directory
    cp -r "$dir" ".${dir/_/}"

    # Delete the underscored directory
    rm -rf "$dir"
  elif [ -d "$dir" ]; then
    # Copy all files from the underscored directory to the period directory
    cp -r "$dir/." ".${dir/_/}"

    # Delete the underscored directory
    rm -rf "$dir"
  fi
done

# ios/_xcode_env to ios/.xcode_env
# code below:
if [ -f "$PROJECT_PATH/ios/_xcode_env" ]; then
  cp -r $PROJECT_PATH/ios/_xcode_env ios/.xcode_env
  rm -rf $PROJECT_PATH/ios/_xcode_env
fi

echo "Init script completed"