#!/usr/bash
echo "Hello World"
# I need to convert back directory _githooks to .githooks
# because .gitignore doesn't allow to add .githooks directory

# step 1: copy all files from _githooks to .githooks
# step 2: delete _githooks directory
# code below:
cp -r _githooks/. .githooks
rm -rf _githooks

# ios/_xcode_env to ios/.xcode_env
# code below:
cp -r ios/_xcode_env ios/.xcode_env
rm -rf ios/_xcode_env

# _eslintignore to .eslintignore
# code below:
cp -r _eslintignore .eslintignore
rm -rf _eslintignore

# _node-version to .node-version
# code below:
cp -r _node-version .node-version
rm -rf _node-version

#
npx yarn install --yes
