image: reactnativecommunity/react-native-android

stages:
  - test
cache:  
  key:    
    files:      
      - Gemfile.lock  
  paths:    
    - vendor/bundle

linter:  
  stage: test
  before_script: #Override a set of commands that are executed before job.
    # - bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs $(nproc) #install bundle in gemfile
    - npx yarn install --yes
  script:    
    - changed_files=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - yarn lint:ci
  environment:
    name: develop
