#!/bin/bash

# setup environment
if [[ "$OSTYPE" == "linux-gnu"* || "$OSTYPE" == "darwin"* || "$(grep -i 'ubuntu' /etc/os-release)" ]]; then
  # rbenv setup
  if which rbenv > /dev/null; then 
    eval "$(rbenv init -)"; 
    rbenv install --skip-existing
  fi
  # check ruby version
  # by get ruby version and matching with .ruby-version
  ruby_version=$(ruby -v | awk '{print $2}')
  echo "Validation ruby_version $ruby_version"
  # load bundle and setup cocoapod, firebase

  if [ "$IGNORE_BUNDLE" = "0" ] || [ "$IGNORE_BUNDLE" = "false" ] || [ -z "$IGNORE_BUNDLE" ]; then 
    echo "Running bundle install"
    gem install bundler
    bundle check || bundle install
  else
    echo "Skipping bundle install"
  fi

  # Load nvm if it is available
  export NVM_DIR="$HOME/.nvm"
  if [ -s "$NVM_DIR/nvm.sh" ]; then
    . "$NVM_DIR/nvm.sh" --no-use
    # Switch to the Node.js version specified in .nvmrc
    # check .nvmrc exists
    eval "[ -f .nvmrc ] && nvm install"
  fi
else
  echo "Skipping npx pod-install as it is only required for macOS."
fi
