#!/bin/bash

# Task 1: Run yarn patch-package --use-yarn
echo "Running yarn patch-package --use-yarn..."
yarn patch-package --use-yarn
echo "Task 1 completed."

# Task 2: Run npx pod-install (only for macOS)
if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "Running npx pod-install..."
  bundle exec npx pod-install
  echo "Task 2 completed."
else
  echo "Skipping npx pod-install as it is only required for macOS."
fi

# Task 4: Run git hook (only for macOS)
# if [[ "$OSTYPE" == "darwin"* ]]; then
#   echo "Running git hook pre commit"
#   git config core.hooksPath .githooks
#   echo "Task 4 completed."
# else
#   echo "Skipping git hook pre commit as it is only required for macOS."
# fi

echo "All tasks completed successfully."
